### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by Arturia169** [AmiyaBot/Amiya-Bot#129]
### 问题描述

无法连接到mirai-api-http
![image](https://user-images.githubusercontent.com/69199123/195983483-14588264-4be5-4148-83ee-0786c69f8fd4.png)

### 复现

启动就会这样

### Amiya-Bot 版本

v6

### 其他插件版本

无

### 日志

```text
这是mirai-api-http的配置

## 启用的 adapter, 内置有 http, ws, reverse-ws, webhook
adapters:
  - http
  - ws

## 是否开启认证流程, 若为 true 则建立连接时需要验证 verifyKey
## 建议公网连接时开启
enableVerify: true
verifyKey: -------------

## 开启一些调式信息
debug: false

## 是否开启单 session 模式, 若为 true，则自动创建 session 绑定 console 中登录的 bot
## 开启后，接口中任何 sessionKey 不需要传递参数
## 若 console 中有多个 bot 登录，则行为未定义
## 确保 console 中只有一个 bot 登陆时启用
singleMode: false

## 历史消息的缓存大小
## 同时，也是 http adapter 的消息队列容量
cacheSize: 4096

## adapter 的单独配置，键名与 adapters 项配置相同
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 8080
    cors: ["*"]
    unreadQueueMaxSize: 100
  
  ## 详情看 websocket adapter 使用说明 配置
  ws:
    host: localhost
    port: 8060
    reservedSyncId: -1

这是mirai的日志
[92m2022-10-15 11:01:06 I/main: Starting mirai-console...[0m[m
[92m2022-10-15 11:01:06 I/main: Backend: version 2.12.1, built on 2022-07-31 09:49:27.[0m[m
[92m2022-10-15 11:01:06 I/main: Frontend Terminal: version 2.12.1, provided by Mamoe Technologies[0m[m
[92m2022-10-15 11:01:06 I/main: Welcome to visit https://mirai.mamoe.net/[0m[m
[91m2022-10-15 11:01:07 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".[0m[m
[91m2022-10-15 11:01:07 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation[0m[m
[91m2022-10-15 11:01:07 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.[0m[m
[92m2022-10-15 11:01:08 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.6.2[0m[m
[92m2022-10-15 11:01:08 I/plugin: Successfully loaded plugin MCL Addon v2.0.2[0m[m
[92m2022-10-15 11:01:08 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop[0m[m
[91m2022-10-15 11:01:08 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key[0m[m
[92m2022-10-15 11:01:08 I/Mirai HTTP API: ********************************************************[0m[m
[91m2022-10-15 11:01:08 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".[0m[m
[91m2022-10-15 11:01:08 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation[0m[m
[91m2022-10-15 11:01:08 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.[0m[m
[92m2022-10-15 11:01:09 I/http adapter: >>> [http adapter] is listening at http://localhost:8080[0m[m
[92m2022-10-15 11:01:09 I/ws adapter: >>> [ws adapter] is listening at ws://localhost:8060[0m[m
[92m2022-10-15 11:01:09 I/Mirai HTTP API: Http api server is running with verifyKey: INITKEYRQOkvNpR[0m[m
[92m2022-10-15 11:01:09 I/Mirai HTTP API: adaptors: [http,ws][0m[m
[92m2022-10-15 11:01:09 I/Mirai HTTP API: ********************************************************[0m[m
[92m2022-10-15 11:01:09 I/MCL Addon: iTXTech MCL Version: 2.1.0-71ec418[0m[m
[91m2022-10-15 11:01:09 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用[0m[m
[92m2022-10-15 11:01:09 I/main: 2 plugin(s) enabled.[0m[m
[91m2022-10-15 11:01:09 W/WindowHelperJvm: Failed to initialize module `java.desktop`
java.lang.UnsatisfiedLinkError: /root/mcl/java/lib/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at java.desktop/java.awt.Toolkit$2.run(Unknown Source)
	at java.desktop/java.awt.Toolkit$2.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.Toolkit.loadLibraries(Unknown Source)
	at java.desktop/java.awt.Toolkit.initStatic(Unknown Source)
	at java.desktop/java.awt.Toolkit.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.mamoe.mirai.utils.WindowHelperJvm.<clinit>(SwingSolver.kt:148)
	at net.mamoe.mirai.utils.LoginSolver.<clinit>(LoginSolver.jvm.kt:92)
	at net.mamoe.mirai.utils.BotConfiguration.<init>(BotConfiguration.kt:221)
	at net.mamoe.mirai.utils.BotConfiguration.<clinit>(BotConfiguration.kt:625)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:186)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:170)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$doStart$10$1.invokeSuspend(MiraiConsoleImplementationBridge.kt:287)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:245)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
	at org.itxtech.mcl.Loader.start(Loader.java:189)
	at org.itxtech.mcl.Loader.main(Loader.java:79)
[0m[m
[92m2022-10-15 11:01:09 I/main: Auto-login 335569218[0m[m
[91m2022-10-15 11:01:10 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...[0m[m
[92m2022-10-15 11:01:11 I/Bot.335569218: Loaded account secrets from local cache.[0m[m
[92m2022-10-15 11:01:11 I/Bot.335569218: Saved account secrets to local cache for fast login.[0m[m
[92m2022-10-15 11:01:11 I/Bot.335569218: Login successful.[0m[m
[0m2022-10-15 11:01:14 V/Bot.335569218: Event: BotOnlineEvent(bot=Bot(335569218))[0m[m
[92m2022-10-15 11:01:14 I/Bot.335569218: Bot login successful.[0m[m
[92m2022-10-15 11:01:14 I/main: mirai-console started successfully.[0m[m

```

**Comment by Initial-heart-1** [comment]
请注意，这并不是一个 Bug，因为它并不是 AmiyaBot 引起的错误，它不应作为一个 Bug 提交。
尽管如此，我检查了你提交的 log。你提交的 log 显示这似乎是由于你的运行环境存在一些问题。你或许应该尝试更换一台设备重复操作来确认是否可以复现该问题。
如果该问题无法复现，那么请尝试重新配置 mirai 及 mirai-api-http。
