### ISSUE TITLE
`amiyabot==1.1.20` 与 Amiya-Bot V6-master 不兼容

### ISSUE THREAD

**Issue by ZhaoZuohong** [AmiyaBot/Amiya-Bot#152]
### 问题描述

发送指令（如“兔兔”）时报错

### 复现

环境：Ubuntu 20.04
1. 按照 <https://www.amiyabot.com/guide/deploy/getStarted.html> 的步骤部署 Amiya-Bot；
2. 安装商店中的“兔兔互动”插件；
3. 群内发送指令（如“兔兔”）

### Amiya-Bot 版本

`bd50e97ae32b12dfbabac08977f2716fdfdcb7e6`

### 其他插件版本

兔兔互动 1.1

### 日志

```text
2022-11-08 22:17:50,563 [     Bot][   ERROR] handler error: Traceback (most recent call last):                       
  File "/Amiya-Bot/venv/lib/python3.8/site-packages/amiyabot/log/manager.py", line 100, in catch                       
    yield                                                                                                           
  File "/Amiya-Bot/venv/lib/python3.8/site-packages/amiyabot/__init__.py", line 49, in __message_handler                                                                                     
    await message_handler(self, event, message)                                                                                                                                         
  File "/Amiya-Bot/venv/lib/python3.8/site-packages/amiyabot/handler/messageHandler.py", line 55, in message_handler                                                                         
    res = await action(data, factory_name)                                                                                  
TypeError: _() takes 1 positional argument but 2 were given
```

### 补充信息

使用 `amiyabot==1.1.19` 正常，更新到 `1.1.20` 后有此问题，回退到 `1.1.19` 正常。

**Comment by vivien8261** [comment]
1.1.20 依赖是昨晚的更新，今天才能适配到这个仓库。

**Comment by ZhaoZuohong** [comment]
Amiya-Bot 更新到 `commit 9de2f637bdd9a6ec12372c1873cd019bb02677d0` 后，使用 `amiyabot==1.1.20` 仍有此问题。

**Comment by vivien8261** [comment]
> Amiya-Bot 更新到 `commit 9de2f637bdd9a6ec12372c1873cd019bb02677d0` 后，使用 `amiyabot==1.1.20` 仍有此问题。

清空所有插件重新安装
