### ISSUE TITLE
[插件BUG]词语替换1.3 BUG    AttributeError: 'Message' object has no attribute 'text_origin'

### ISSUE THREAD

**Issue by EternalBook** [AmiyaBot/Amiya-Bot#174]
### 问题描述

![RG3NES8GQ)`R7Y1BMKK 39X](https://user-images.githubusercontent.com/52482646/215672914-a80b66fc-8d64-4678-88f6-384a01ed4a7a.png)
AttributeError: 'Message' object has no attribute 'text_origin'
系统：Debian
python3.9

### 复现

是可以复现的BUG 不单是词语替换插件

### Amiya-Bot 版本

6.0.11

### 日志

```text
2023-01-31 13:22:14,969 [     Bot][   ERROR] handler error: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/amiyabot/log/manager.py", line 100, in catch
    yield
  File "/usr/local/lib/python3.9/dist-packages/amiyabot/__init__.py", line 59, in __message_handler
    await message_handler(self, event, message)
  File "/usr/local/lib/python3.9/dist-packages/amiyabot/factory/messageHandler.py", line 36, in message_handler
    data = await middleware(data) or data
  File "/root/Amiya-Bot/plugins/amiyabot-replace-1_3/main.py", line 68, in _
    text = data.text_origin
AttributeError: 'Message' object has no attribute 'text_origin'
```

**Comment by vivien8261** [comment]
依赖降级到 1.2.7
```
pip install amiyabot==1.2.7
```
