### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by ProDong0512** [AmiyaBot/Amiya-Bot#180]
### 问题描述

在第一次启动（python amiya.py）时，下载到一半要求提供gitee账号密码，并在输入账密正确后仍报错。手动打开对应的下载地址，https://gitee.com/amiya-bot/arknights-resource-skins.git，得到访问受限（403）。推测可能是该资源现在被上了权限？

exe部署是成功的。

### 复现

可能可以通过重新部署的方式触发提供账密，然后输入一个新创的gitee账号？或许可以复现

### Amiya-Bot 版本

6.0.13-Beta

### 其他插件版本

无

### 日志

```text
$ python amiya.py
# jionlp - ΢▒Ź▒▒ں▒: JioNLP  Github: `https://github.com/dongrixinyu/JioNLP`.
# jiojio - `http://www.jionlp.com/jionlp_online/cws_pos` is available for online trial.
2023-02-26 11:50:08,789 [    Main][    INFO] fetching repo: https://gitee.com/amiya-bot/arknights-resource.git...
2023-02-26 11:50:09,473 [    Main][    INFO] fetching repo: https://gitee.com/amiya-bot/arknights-resource-skins.git...
Traceback (most recent call last):
  File "amiya.py", line 16, in <module>
    load_resource()
  File "E:\amiya\Amiya-Bot\core\__init__.py", line 78, in load_resource
    GitAutomation(f'{gamedata_path}/{path}', url).update()
  File "E:\amiya\Amiya-Bot\core\lib\gitAutomation.py", line 42, in update
    git.Repo.clone_from(self.repo_url, to_path=self.repo_dir, progress=self.progress)
  File "C:\Users\Pioneer\anaconda3\lib\site-packages\git\repo\base.py", line 1325, in clone_from
    return cls._clone(
  File "C:\Users\Pioneer\anaconda3\lib\site-packages\git\repo\base.py", line 1221, in _clone
    handle_process_output(
  File "C:\Users\Pioneer\anaconda3\lib\site-packages\git\cmd.py", line 204, in handle_process_output
    return finalizer(process)
  File "C:\Users\Pioneer\anaconda3\lib\site-packages\git\util.py", line 419, in finalize_process
    proc.wait(**kwargs)
  File "C:\Users\Pioneer\anaconda3\lib\site-packages\git\cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --progress -- https://gitee.com/amiya-bot/arknights-resource-skins.git resource/gamedata/skin
```

### 补充信息

无

**Comment by vivien8261** [comment]
资源被限制了，正在尝试解决

**Comment by vivien8261** [comment]
已修复
