### ISSUE TITLE
安装插件出错

### ISSUE THREAD

**Issue by Rovniced** [AmiyaBot/Amiya-Bot#187]
### 问题描述

在安装插件 词语替换 明日方舟干员资料均报错 提示安装失败
报错日志1

在安装 插件pixiv搜图 出现以下报错
报错日志2

### 复现

安装插件出现此问题，即使在未装任何插件时候也会出现此问题

### Amiya-Bot 版本

6.0.14

### 日志

```text
错误日志1：
2023-03-08 22:55:10,183BotERRORplugin install error: Traceback (most recent call last): 
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\amiyabot\log\manager.py", line 116, in sync_catch 
    yield 
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\amiyabot\factory\__init__.py", line 295, in load_plugin 
    module = importlib.import_module(os.path.basename(dest)) 
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module 
    return _bootstrap._gcd_import(name[level:], package, level) 
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import 
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load 
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked 
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked 
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module 
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed 
  File "C:\Users\Administrator\Desktop\Amiya-Bot-6-master\plugins\arknights-operator-m&c-2_6\__init__.py", line 1, in <module> 
    from .main import bot 
  File "C:\Users\Administrator\Desktop\Amiya-Bot-6-master\plugins\arknights-operator-m&c-2_6\main.py", line 4, in <module> 
    from amiyabot.adapters.mirai import MiraiForwardMessage 
ImportError: cannot import name 'MiraiForwardMessage' from 'amiyabot.adapters.mirai' (C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\amiyabot\adapters\mirai\__init__.py) 

报错日志2
![image](https://user-images.githubusercontent.com/52170460/223750129-d1e0d667-6e1a-47cd-8aac-100778350062.png)
```

**Comment by Initial-heart-1** [comment]
插件使用了当前适配器不兼容的方法。不是 bug。至少不应该在这里提。

**Comment by Rovniced** [comment]
> 词语替换 明日方舟干员资料均报错

但是 词语替换 明日方舟干员资料 这2个不是官方插件吗？

**Comment by Initial-heart-1** [comment]
插件相关请转至 AmiyaBot/Amiya-Bot-plugins。
该 issue 提到的相关问题应该已经修复，未修复则请前往频道插件相关板块反馈。
