### ISSUE TITLE
python amiya.py失败，提示type error

### ISSUE THREAD

**Issue by Anya0331** [AmiyaBot/Amiya-Bot#196]
### 问题描述

在新服务器上部署amiyabot，提示如下：
`Traceback (most recent call last):
  File "amiya.py", line 4, in <module>
    import core.frozen
  File "/usr/amiya/Amiya-Bot/core/__init__.py", line 164, in <module>
    async def _(err: Exception, instance: BotAdapterProtocol, data: Union[Message, Event]):
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/factory/__init__.py", line 138, in handler
    for item in exceptions:
TypeError: 'type' object is not iterable`

python module amiyabot版本为1.3.10

admin@:/usr/amiya/Amiya-Bot$ pip3 list
Package                Version             
aiohttp                3.7.4.post0         
amiyabot               **1.3.10**

查询/usr/local/lib/python3.8/dist-packages/amiyabot/factory/__init__.py，发现def on_exception方法可能有问题：
‘    
        def handler(func: ExceptionHandlerType):
            nonlocal exceptions

            **if isinstance(exceptions, list):
                exceptions = [exceptions]**

            exception_handlers = self.get_container('exception_handlers')

            for item in exceptions:
                if item not in exception_handlers:
                    exception_handlers[item] = []

                exception_handlers[item].append(func)

            return func’

`            if isinstance(exceptions, list):
                exceptions = [exceptions]`这一段有问题吧？

### 复现

python 模块 amiyabot=1.3.10

### Amiya-Bot 版本

6.0.15-rc3

**Comment by Anya0331** [comment]
另一台服务器上amiyabot=1.3.2
同文件if语句为
if type(exceptions) is not list:                                                                 
                exceptions = [exceptions] 
无问题

**Comment by vivien8261** [comment]
pip install --upgrade amiyabot==1.3.10

**Comment by vivien8261** [comment]
按错了……
