### ISSUE TITLE
安装程序出错

### ISSUE THREAD

**Issue by ghost** [AmiyaBot/Amiya-Bot#203]
### 问题描述

# jionlp - 微信公众号: JioNLP  Github: `https://github.com/dongrixinyu/JioNLP`.
# jiojio - `http://www.jionlp.com/jionlp_online/cws_pos` is available for online trial.
2023-04-12 20:11:54,514 [    Main][    INFO] fetching repo: https://gitee.com/amiya-bot/arknights-resource.git...
2023-04-12 20:11:55,307 [    Main][    INFO] fetching repo: https://gitee.com/amiya-bot/arknights-resource-skins.git...
2023-04-12 20:11:57,899 [    Main][    INFO] checking assets update...
Traceback (most recent call last):
  File "amiya.py", line 16, in <module>
  File "core\__init__.py", line 69, in load_resource
  File "core\resource\botResource.py", line 44, in download_bot_resource
Exception: assets download failed
[25944] Failed to execute script 'amiya' due to unhandled exception!

### 复现

下载可执行文件
运行exe

### Amiya-Bot 版本

AmiyaBot-v6.1.0-fix-master.exe

**Comment by ghost** [comment]
2023-04-13 01:58:34,885 [    Main][    INFO] checking assets update...
Traceback (most recent call last):
  File "E:\AmiyaBotConsole\amiya.py", line 16, in <module>
    load_resource()
  File "E:\AmiyaBotConsole\core\__init__.py", line 72, in load_resource
    BotResource.download_bot_resource()
  File "E:\AmiyaBotConsole\core\resource\botResource.py", line 53, in download_bot_resource
    raise Exception(f'assets download failed')
Exception: assets download failed

**Comment by ghost** [comment]
我重新使用命令行的方式安装，依然没有作用，推荐增加更多下载渠道来解决这个问题，例如就放到github上而不是用gitte，现在我很烦恼

**Comment by ghost** [comment]
E:\AmiyaBotConsole>python amiya.py
# jionlp - 微信公众号: JioNLP  Github: `https://github.com/dongrixinyu/JioNLP`.
# jiojio - `http://www.jionlp.com/jionlp_online/cws_pos` is available for online trial.
2023-04-13 02:12:38,725 [    Main][    INFO] fetching repo: https://gitee.com/amiya-bot/arknights-resource.git...
2023-04-13 02:12:39,597 [    Main][    INFO] fetching repo: https://gitee.com/amiya-bot/arknights-resource-skins.git...
2023-04-13 02:12:39,600 [    Main][    INFO] fetching repo: https://gitee.com/amiya-bot/arknights-resource-skins.git...
fetching [=========================] 12.0 / 12.0 (100%)
fetching [=========================] 12.0 / 12.0 (100%)
fetching [=========================] 11.0 / 11.0 (100%)
fetching [=========================] 11.0 / 11.0 (100%)
fetching [=========================] 12.0 / 12.0 (100%) 409.44 MiB | 9.51 MiB/s
fetching [=========================] 12.0 / 12.0 (100%) 411.52 MiB | 10.09 MiB/s
2023-04-13 02:13:46,552 [    Main][    INFO] checking assets update...
Traceback (most recent call last):
  File "amiya.py", line 16, in <module>
    load_resource()
  File "E:\AmiyaBotConsole\core\__init__.py", line 69, in load_resource
    BotResource.download_bot_resource()
  File "E:\AmiyaBotConsole\core\resource\botResource.py", line 44, in download_bot_resource
    raise Exception(f'assets download failed')
Exception: assets download failed

E:\AmiyaBotConsole>pause
请按任意键继续. . .

**Comment by ghost** [comment]
emmmmmmm我翻了半天源代码，大致估计错误位置在sasets.txt这，我手写了一个文件./resrouces/sastes-lock.txt就解决了？？？？而且里面还是空文档

**Comment by ghost** [comment]
确定可以通过这种方式解决了没有影响，当出现如上问题时可以在resrouces文件夹下创建一个名为sassets-lock.txt的文件解决

**Comment by ghost** [comment]
不过依然希望官方能从代码上面解决这个问题

**Comment by Initial-heart-1** [comment]
那么请你重新打开一个 issue。关闭的 issue 一般不会被处理。

**Comment by ghost** [comment]
> 那么请你重新打开一个 issue。关闭的 issue 一般不会被处理。

我已经将这个问题解决了，解决方案也贴在上面，不过只能算是一个临时方案，代码我不知道怎么改因为看代码里面还涉及更新这样弄多半是不行的

**Comment by vivien8261** [comment]
这个报错是资源下载失败，请你确认你的网络环境能够访问官方的 cos 资源库（比如开了代理）。你手动添加 assets-lock.txt 相当于阻止了资源下载，会导致某些插件无法安装。
