### ISSUE TITLE
明日方舟干员资料报错

### ISSUE THREAD

**Issue by desktop4025** [AmiyaBot/Amiya-Bot#211]
### 问题描述

我依次尝试了功能，只有基础资料，材料和技能会报错
![图片](https://github.com/AmiyaBot/Amiya-Bot/assets/107090995/dcd015be-4352-4b13-b920-27aa5b406772)

### 复现

说兔兔查看干员的时候

### Amiya-Bot 版本

AmiyaBot-demo-v6

### 补充信息

[running.zip](https://github.com/AmiyaBot/Amiya-Bot/files/11443760/running.zip)

**Comment by Initial-heart-1** [comment]
Python 版本多少？

**Comment by vivien8261** [comment]
不是最新代码，拉最新的master代码。

**Comment by desktop4025** [comment]
> 不是最新代码，拉最新的master代码。

已更新，还是报错欸，python是3.10.9，还多了一个报错不知道是啥情况
2023-05-11 11:14:11,727 [    Main][   ERROR] fail to request <https://backend.yituliu.site/stage/t3?expCoefficient=0.625>[GET]
2023-05-11 11:14:11,730 [    Main][   ERROR] yituliu data save error: Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\amiyabot\log\manager.py", line 100, in catch
    yield
  File "D:\Git\Amiya-Bot\plugins\amiyabot-arknights-material-1_9\main.py", line 43, in save_yituliu_data
    t3 = json.loads(t3)
  File "C:\ProgramData\anaconda3\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
2023-05-11 11:14:12,641 [    Main][    INFO] browser(chromium) launched successful.
2023-05-11 11:14:12,645 [   Mirai][    INFO] connecting websocket(3487423593)...
2023-05-11 11:14:12,650 [   Mirai][    INFO] websocket(3487423593) connect successful. waiting handshake...
2023-05-11 11:14:12,653 [   Mirai][    INFO] websocket(3487423593) handshake successful. session: t368thDf
2023-05-11 11:16:21,279 [   Mirai][    INFO] Bot:3487423593 Channel:514196567 User:1223063346 　: 兔兔查看塞雷娅
2023-05-11 11:16:22,272 [    Main][   ERROR] handler error: Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\amiyabot\log\manager.py", line 100, in catch
    yield
  File "C:\ProgramData\anaconda3\lib\site-packages\amiyabot\__init__.py", line 72, in __message_handler
    await message_handler(self, data)
  File "C:\ProgramData\anaconda3\lib\site-packages\amiyabot\handler\messageHandler.py", line 70, in message_handler
    reply = await handler.action(data)
  File "C:\ProgramData\anaconda3\lib\site-packages\amiyabot\factory\implemented.py", line 100, in action
    return await self.function(data)
  File "D:\Git\Amiya-Bot\plugins\amiyabot-arknights-operator-2_7\main.py", line 268, in _
    result, tokens = await OperatorData.get_operator_detail(info)
  File "D:\Git\Amiya-Bot\plugins\amiyabot-arknights-operator-2_7\operatorData.py", line 34, in get_operator_detail
    skills, skills_id, skills_cost, skills_desc = operator.skills()
  File "D:\Git\Amiya-Bot\core\resource\arknightsGameData\operatorBuilder.py", line 233, in skills
    for lev, cond in enumerate(item['levelUpCostCond']):
KeyError: 'levelUpCostCond'

**Comment by vivien8261** [comment]
https://github.com/AmiyaBot/Amiya-Bot/blob/V6-master/core/resource/arknightsGameData/operatorBuilder.py#L233

最新代码 233 行已经不是这样的了，再报错你要自查你的 git pull 能不能正确执行。

**Comment by desktop4025** [comment]
> 

好的谢谢

**Comment by Initial-heart-1** [comment]
推荐使用py3.8，不过这个应该不是重点。

**Comment by desktop4025** [comment]
> 推荐使用py3.8，不过这个应该不是重点。

没有问题了，是我仓库克隆错了，谢谢
