### ISSUE TITLE
assets download failed

### ISSUE THREAD

**Issue by ghost** [AmiyaBot/Amiya-Bot#235]
### 问题描述

在使用exe部署失败后，我尝试了代码部署，仍未成功，命令行输出
# jionlp - 微信公众号: JioNLP  Github: `https://github.com/dongrixinyu/JioNLP`.
# jiojio - `http://www.jionlp.com/jionlp_online/cws_pos` is available for online trial.
2023-08-05 21:01:34,400 [    Main][    INFO] checking assets update...
Traceback (most recent call last):
  File "amiya.py", line 33, in <module>
    run_amiya(
  File "amiya.py", line 12, in run_amiya
    BotResource.download_bot_resource()
  File "D:\Programming\Amiya-Bot\core\resource\botResource.py", line 44, in download_bot_resource
    raise Exception(f'assets download failed')
Exception: assets download failed
sys:1: RuntimeWarning: coroutine 'load_plugins' was never awaited
sys:1: RuntimeWarning: coroutine 'HttpServer.serve' was never awaited
sys:1: RuntimeWarning: coroutine 'MultipleAccounts.start' was never awaited

### 复现

我配置了go-cqhttp，通过exe配置报错assets download failed，便改用代码配置，但报了这个错
主机是能够连上amiya bot下载所需的资源的，我尝试手动下载了Amiya-Bot-assets.zip并放入指定文件夹依然未解决

### Amiya-Bot 版本

6.3.4

### 日志

```text
D:\Programming\Amiya-Bot\log\running.log
2023-08-05 21:01:34,400 [    Main][    INFO] checking assets update...
```

**Comment by Initial-heart-1** [comment]
根据您目前提供的信息判断，user error
您的网络状况可能不太好，可以尝试使用 ssh 连接。
如有问题请 reopen issue。
