### ISSUE TITLE
最新版出现报错

### ISSUE THREAD

**Issue by fatinghenji** [AmiyaBot/Amiya-Bot#51]
```python3
root@localhost:~/Amiya-Bot# python3 amiya.py 
[2022-01-09 00:31:40][INFO] Starting AmiyaBot...
[2022-01-09 00:31:40][INFO] Init http session: TA5hE872
[2022-01-09 00:31:40][INFO] Release session: TckLvaHM
[2022-01-09 00:31:40][INFO] Checking GameData update...
[2022-01-09 00:31:40][INFO] GameData version is up to date: 24.2.0
[2022-01-09 00:31:40][INFO] [=========================] 100% 15/15 (15 TT, 15 OK, 0 NG) <gameData>
[2022-01-09 00:31:40][INFO] Checking Console update...
[2022-01-09 00:31:41][INFO] Console version is up to date: 1637233491718
[2022-01-09 00:31:41][INFO] [=========================] 100% 16/16 (16 TT, 16 OK, 0 NG) <console>
[2022-01-09 00:31:41][INFO] [=========================] 100% 16/16 (16 TT, 16 OK, 0 NG) <face>
[2022-01-09 00:31:41][INFO] [=========================] 100% 3/3 (3 TT, 3 OK, 0 NG) <style>
[2022-01-09 00:31:41][INFO] [=========================] 100% 8/8 (8 TT, 8 OK, 0 NG) <class>
[2022-01-09 00:31:41][INFO] [=========================] 100% 7/7 (7 TT, 7 OK, 0 NG) <gacha>
[2022-01-09 00:31:41][INFO] [=========================] 100% 2/2 (2 TT, 2 OK, 0 NG) <database>
[2022-01-09 00:31:41][INFO] [=========================] 100% 70/70 (13 TT, 13 OK, 0 NG) <AmiyaVoices>
[2022-01-09 00:31:42][INFO] [                         ] 0% 0/225 (0 TT, 0 OK, 0 NG) <operators>Traceback (most recent call last):
  File "/root/Amiya-Bot/amiya.py", line 42, in <module>
    amiya = Main()
  File "/root/Amiya-Bot/amiya.py", line 19, in __init__    self.handlers = Handlers(self)
  File "/root/Amiya-Bot/handlers/handleMessage.py", line 19, in __init__
    super().__init__(bot)
  File "/root/Amiya-Bot/handlers/functions/__init__.py", line 23, in __init__
    self.arknights = Arknights(bot)
  File "/root/Amiya-Bot/handlers/functions/arknights/__init__.py", line 12, in __init__
    super().__init__(auto_update=True, check_assets=True)
  File "/root/Amiya-Bot/dataSource/__init__.py", line 31, in __init__
    self.download_operators_images(self.operators)
  File "/root/Amiya-Bot/dataSource/__init__.py", line 183, in download_operators_images
    res = self.get_pic(f'portrait/{item.id}_1', 'portraits')
  File "/root/Amiya-Bot/dataSource/sourceBank.py", line 66, in get_pic
    escape_name = name.repalce("#", "%23")
AttributeError: 'str' object has no attribute 'repalce'
```

**Comment by vivien8261** [comment]
#50 已修复
