### ISSUE TITLE
访问网页控制台报Internal Server Error错误

### ISSUE THREAD

**Issue by chenjie1234567890** [AmiyaBot/Amiya-Bot#58]
操作系统:windows10
软件版本：AmiyaBot-v5.0.5.exe
启动方式：浏览器访问127.0.0.1:5000

错误日志：
[2022-03-09 08:32:56][INFO] Server.access - 127.0.0.1:6899 - GET / HTTP/1.1 500 Internal Server Error
[2022-03-09 08:33:01][INFO] Server.default - Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 364, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 61, in app
  File "fastapi\routing.py", line 226, in app
  File "fastapi\routing.py", line 159, in run_endpoint_function
  File "core\network\httpServer\__init__.py", line 81, in index
  File "starlette\templating.py", line 89, in TemplateResponse
  File "starlette\templating.py", line 76, in get_template
  File "jinja2\environment.py", line 997, in get_template
  File "jinja2\environment.py", line 958, in _load_template
  File "jinja2\loaders.py", line 125, in load
  File "jinja2\loaders.py", line 214, in get_source
jinja2.exceptions.TemplateNotFound: index.html

**Comment by chenjie1234567890** [comment]
问题已解决，原因：缺少静态文件，重新下载即可
